### ISSUE TITLE
problems with default settings for output

### ISSUE THREAD

**Issue by najoshi** [ibest/HTStream#125]
So the default settings for output (for any of the software) is outputting to fastq format (which isn't clear from the help).... when I ran a pipeline, but I forgot to specify "-O" for stdout for the first thing in the pipeline, the default wrote to a file. So then the rest of software in the pipeline (since they didn't get any input) had no output and silently failed. Instead of having a default output format, you should force the user to choose an output format every time. I.e. no default.

**Comment by msettles** [comment]
Pull request #139 handles this issue, requiring an output type be specified removing the default

**Comment by samhunter** [comment]
How about instead of forcing a user to choose an output, we always output to stdout (so that it streams naturally) and you have to choose an output format if you want it to go to a file? This seems to fit better with normal linux tools (cat etc) and with tools like bwa or samtools.

**Comment by msettles** [comment]
That seems reasonable to me, can make that change



On July 10, 2018 at 1:56:16 PM, Hunter Sam (notifications@github.com) wrote:

How about instead of forcing a user to choose an output, we always output
to stdout (so that it streams naturally) and you have to choose an output
format if you want it to go to a file? This seems to fit better with normal
linux tools (cat etc) and with tools like bwa or samtools.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ibest/HTStream/issues/125#issuecomment-403963032>, or mute
the thread
