### ISSUE TITLE
Phix-remover comments/issue/questions

### ISSUE THREAD

**Issue by msettles** [ibest/HTStream#62]
How were the parameters chosen, just in a quick test the new Phix-remover identified twice as many reads as phix as the old bowtie2 local method. Not saying this isn't correct, but curious as to what was done to validate. 

why print the WHOLE phiX on help, can probably reduce via ... 
default
-x [ --hits ] arg (=50)   How many 8-mer hits to phix needs to happen to discard

What happens if there isn't 50 kmers (short --seq), or wouldn't it be better to do a % perfect kmers of the shorter of seq or read? Something like that

Stats.out output isn't consistent with other sub-apps stats output

**Comment by dstreett** [comment]
Yeah, so the parameter was randomly picked. 50 sounded like a good number. I'm going through validation now and I'm really happy to hear this result since it suggest further tuning is required.

@samhunter and @msettles Yeah, %kmer might make more sense. Also, I can add in the option to change the kmer length to further add to the tuning.

I'll dive into the stats issue.

**Comment by msettles** [comment]
ON this, I also tried to read your code, I for the life of me can’t figure out what your doing! Any way you can quickly comment the code, I’d like to add a variant to dbcAmplicons, screen for and get %phix in the run.


Matt

**Comment by dstreett** [comment]
So, some pretty wacky zany code for sure.

So, I'm assuming you are checking out phix_remover.h? The two import functions are setLookup and check_read.

So, big picture. setLookup goes through whatever sequence was inputted and breaks the sequence into perfect 8mers that are translated to binary (both forward and reverse strands). This binary kmers are used to add a “hit” to the proper lookup table (one for forward and one for reverse). The lookup table in this case is an array, since a binary 8mer only has approximately 65k possible locations. This means we have a constant lookup time.

check_read does the same perfect overlapping 8mer binary, except only in the forward direction. It will check the 8mer hits on both the forward and reverse lookup tables. If there is a hit, either hits or hits_rc will be incremented. The largest resulting value between hits and hits_rc is returned. If there are enough hits to the kmer lookup table, then the read is discarded.

I’ll comment specifics in the code, but this is the general idea.

**Comment by msettles** [comment]
So close for now, continued testing needed will reopen if issues arrise
