### ISSUE TITLE
NRemover will ignore 1 bp of N

### ISSUE THREAD

**Issue by dstreett** [ibest/HTStream#81]
Just a note to fix it

**Comment by msettles** [comment]
has it been fixed?

**Comment by msettles** [comment]
So out of curiosity, to figure out if this issue can be closed or not I tried the test read
        const std::string readData_7 = "@Read1\nGTTTTAGGATTNTTTTTTTTTTA\n+\n#######################\n";
So here the N is right in the middle 11bp to the left 11bp to the right, I would say the app should return the left string GTTTTAGGATT, but instead it returns the tail TTTTTTTTTA. The head is likely better quality and so should trim right to left, rather than left to right

**Comment by msettles** [comment]
Dealt with in pull request #114
